### ISSUE TITLE
Panning the canvas stopped working after updating dependencies

### ISSUE THREAD

**Issue by eyuelt** [tessa3/uxgraph#107] opened 2016-11-22 09:33 UTC
After further investigation, it looks like this issue only happens when the page is loaded or refreshed on the home page and then switched to the graph page. If the page is reloaded while on the graph page, panning works again.

Also, it's not only panning on the canvas that's not working. All change detection on the graph page is disabled. I tried creating a simple counter component and putting it in the graph-header, and it has the same behavior. It only works if you refresh the page while on the graph page.

The call stack in the debugger shows that the data update is already happening within a zone, but for some reason, if I inject NgZone and wrap the data update within a zone.run() call, then it works. Even though, according to the debugger, that code was already in a zone to begin with.

Next action:
Use [git bisect](https://robots.thoughtbot.com/git-bisect) to figure out exactly which commit caused this regression. Then figure out which dependency caused it.

**Comment by eyuelt** [comment] 2016-11-25 05:28
Confirmed that this is the change that causes the issue:

```
-    "@angular/common": "2.0.0-rc.5",
-    "@angular/compiler": "2.0.0-rc.5",
-    "@angular/core": "2.0.0-rc.5",
-    "@angular/forms": "0.3.0",
-    "@angular/http": "2.0.0-rc.5",
-    "@angular/platform-browser": "2.0.0-rc.5",
-    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
+    "@angular/common": "2.2.1",
+    "@angular/compiler": "2.2.1",
+    "@angular/core": "2.2.1",
+    "@angular/forms": "2.2.1",
+    "@angular/http": "2.2.1",
+    "@angular/platform-browser": "2.2.1",
+    "@angular/platform-browser-dynamic": "2.2.1",
```

**Comment by eyuelt** [comment] 2016-11-26 06:57
The issue was that the `graphPreviews` list in `home.component.ts` was being populated outside of a zone. Populating `graphPreviews` causes the links for each graph page to be created, so the links are being created outside of a zone. I'm not sure why that means that clicking the link creates the graph page outside of a zone. Maybe `@angular/router` somehow keeps track of the zone that the link was created in, then creates the linked page within that same zone.

More importantly, I don't know why the code is being run outside of a zone in the first place. It's in the callback that is passed to an observable defined in `GoogleRealtimeService`. Doesn't angular make sure observables' callbacks are run in zones? Or do we need to manually handle that?

@girum11, do you know (or can you figure out) what we need to do to get observables and zones working together?

**Comment by girum11** [comment] 2016-11-27 23:45
Nice, thanks for finding this. I'm going to close out #80 as a dupe of this.

I don't think Observables are what's running outside of the zone, I think it's the gapi library that runs the callback in the first place. I think you should try pushing this "run it within a zone" callback deeper into the `GoogleRealtimeService` so that clients don't have to see the ugliness.

~

I don't think I know how to get gapi and Angular 2's CD to play well together outside of just running gapi callbacks within the zones. There may be some other way; if it gets annoying we can ask an Angular 2 Google Group about it.

**Comment by eyuelt** [comment] 2016-12-10 20:03
Found another issue with the same problem: https://github.com/angular/angular/issues/7792

I wish I'd found it sooner, as it suggests using `Zone.current.name`, which turned out to be really helpful in understanding what's going on.

**Comment by eyuelt** [comment] 2016-12-10 20:22
**It's fixed!**  🎉 🎉 🎉 

To recap: the issue is that gapi doesn't respect Zone.js. When you call a gapi method from within the angular zone, you would expect any callback you pass in to the method to also be called within that zone, but this is not the case.

Probably gapi is doing some weird stuff to schedule the callback to be executed asynchronously. If it was using normal stuff like setTimeout or something, it would've used the monkey-patched version provided by the angular zone, which would cause the callback to be run in the angular zone, as expected.

**Comment by eyuelt** [comment] 2016-12-10 20:24
Though I still don't know why this didn't happen until we updated to angular 2.2.1. 🤔

**Comment by eyuelt** [comment] 2016-12-10 21:07
Tested with 6bf55bf978a921bf0063b4830aba6bb15388e9f7 (right before angular 2.2.1 update) and gapi has the same behavior, which makes sense since we didn't change the gapi version.

What has changed is angular's behavior when changing routes. Apparently, before 2.2.1, clicking on a router link would execute within the angular zone, even if the router link element was created outside of the angular zone. But this is not true from 2.2.1 onwards. Now, it executes in the zone the router link element was created in.

In our case, `GoogleRealtimeService.listFiles` returns the list of graph files outside of the angular zone, so the graph-previews (which are router links) on the home page all get created outside of the angular zone. Clicking on a graph-preview goes to the graph page, so it calls the graph constructor. The console screenshots below demonstrate the difference in behavior in this case.

**Angular 2.0.0-rc.5:**
The graph is created in the angular zone.

![screen shot 2016-12-10 at 12 44 58 pm](https://cloud.githubusercontent.com/assets/1365480/21076104/fd98d2ae-bed7-11e6-977e-833ed26fe385.png)

**Angular 2.2.1:**
The graph is created outside of the angular zone, in the root zone.

![screen shot 2016-12-10 at 1 05 31 pm](https://cloud.githubusercontent.com/assets/1365480/21076170/72e75a8e-bed9-11e6-95bf-0c214f4abf7b.png)

**Closed** 2016-12-11 23:14 UTC
Labels: bug
